#!/bin/bash

# Docker 镜像管理器 - 快速开始指南

echo "🐳 Docker 镜像管理器 - 安装指南"
echo "================================"
echo ""
echo "请按照以下步骤安装和运行："
echo ""
echo "1️⃣  安装 pip（如果尚未安装）："
echo "   sudo apt update && sudo apt install -y python3-pip"
echo ""
echo "2️⃣  安装依赖："
echo "   pip3 install -r requirements.txt"
echo ""
echo "3️⃣  数据库迁移："
echo "   python3 manage.py makemigrations"
echo "   python3 manage.py migrate"
echo ""
echo "4️⃣  运行服务："
echo "   python3 manage.py runserver 0.0.0.0:8000"
echo ""
echo "5️⃣  访问应用："
echo "   打开浏览器访问 http://localhost:8000"
echo ""
echo "📝 或者使用 Docker Compose 运行："
echo "   docker-compose up -d"
echo ""
echo "================================"
